version: '3.4'

services:
  dockermysql:
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345atomdev
      MYSQL_USER: atomdevadmin
      MYSQL_PASSWORD: 12345atomdev
      MYSQL_DATABASE: ViribusUnitis
    volumes:
      - /usr/mysql:/var/lib/mysql
      #- ./API_AtomHack/Migration.sql:/docker-entrypoint-initdb.d/1.sql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
  viribus_unitis:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=Viribus_Unitis.pfx 
    depends_on: 
      dockermysql:
         condition: service_healthy
    ports:
      - 5000:8080
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  proxy:
    image: nginx:latest
    depends_on: 
      - viribus_unitis
    volumes:
      - ./Viribus_Unitis/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80